Extension { #name : #FAMIXEntity }

{ #category : #'*Ada-Entities-FAMIX' }
FAMIXEntity >> getArgVariable [
	^ nil
]

{ #category : #'*Ada-Entities-FAMIX' }
FAMIXEntity >> isAdaContainer [
	^ false
]

{ #category : #'*Ada-Entities-FAMIX' }
FAMIXEntity >> isAdaPackage [
	^ false
]

{ #category : #'*Ada-Entities-FAMIX' }
FAMIXEntity >> isAdaStructural [
	^ false
]

{ #category : #'*Ada-Entities-FAMIX' }
FAMIXEntity >> isAdaSubprogram [
	^ false
]

{ #category : #'*Ada-Entities-FAMIX' }
FAMIXEntity >> isAdaTask [
	^ false
]

{ #category : #'*Ada-Entities-FAMIX' }
FAMIXEntity >> isAdaType [
	^ false
]

{ #category : #'*Ada-Entities-FAMIX' }
FAMIXEntity >> isAdaUnknownContainer [
	^ false
]

{ #category : #'*Ada-Entities-FAMIX' }
FAMIXEntity >> isTopLevelContainer [
	^ false
]
