Extension { #name : #UndefinedObject }

{ #category : #'*Ada-Entities-FAMIX' }
UndefinedObject >> getArgVariable [
	^ nil
]

{ #category : #'*Ada-Entities-FAMIX' }
UndefinedObject >> isAdaContainer [
	^ false
]

{ #category : #'*Ada-Entities-FAMIX' }
UndefinedObject >> isAdaPackage [
	^ false
]

{ #category : #'*Ada-Entities-FAMIX' }
UndefinedObject >> isAdaStructural [
	^ false
]

{ #category : #'*Ada-Entities-FAMIX' }
UndefinedObject >> isAdaSubprogram [
	^ false
]

{ #category : #'*Ada-Entities-FAMIX' }
UndefinedObject >> isAdaTask [
	^ false
]

{ #category : #'*Ada-Entities-FAMIX' }
UndefinedObject >> isAdaType [
	^ false
]
